version: '2'
services:
server:
    container_name: server
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file: .env
    volumes:
      - ./server:/app
  db:
    image: postgres:latest
    restart: always
    # volumes:
    #   - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
