export default {
  user: 'user',
  item_type: 'item_type',
  city: 'city',
  country: 'country',
  shape: 'shape',
  location: 'location',
  address: 'address',
  manufacturer: 'manufacturer',
  size: 'size',
  item: 'item',
  item_info: 'item_info',
  item_image: 'item_image',
  related_item: 'related_item',
};
